/**
 * hybrid-adapter.ts — HybridMemoryAdapter (Phase 3.3)
 *
 * Architecture: "User-Powered" Memory
 *
 *   Local Vector DB (sqlite-vec, server-side Node.js)
 *     → fast similarity search, <10ms, in-process
 *     → capped at 10 most recent memory vectors per user (5-10 rule)
 *     → embeddings generated by the already-configured embedding providers
 *
 *   Firestore (text backup only — no vectors stored in cloud)
 *     → /users/{userId}/memory/{memoryId} with text + metadata only
 *     → vectors are never sent to Firestore (saves cost + bandwidth)
 *     → on cold start (empty local DB), last 10 text snippets are fetched
 *       from Firestore and re-embedded locally to rehydrate the active memory
 *
 * Why this design:
 *   - Zero vector search infrastructure cost (no Vertex AI, no Pinecone)
 *   - Scales to millions of users: each user's memory is isolated and tiny
 *   - Cloud persistence: memory survives server restarts and horizontal scaling
 *   - Privacy: raw vectors never leave the server process that owns them
 *
 * The 5-10 Rule:
 *   After every INSERT, keep only the 10 most recent memories in the local DB.
 *   This bounds memory size, keeps search fast, and prevents unbounded growth.
 *   The full text history lives in Firestore — the local DB is the "active context."
 *
 * Relationship to MemorySearchManager:
 *   This adapter wraps the existing MemorySearchManager interface. All search
 *   calls go through the local sqlite-vec index. Firestore is only touched on
 *   insert (sync) and on cold start (rehydration). The agent runtime does not
 *   know this adapter exists — it calls the MemorySearchManager interface.
 */

import type { MemorySearchManager, MemorySearchResult, MemoryEmbeddingProbeResult, MemoryProviderStatus } from './types.js';
import logger from '../utils/logger.js';

// ── Dependency Interfaces ─────────────────────────────────────────────────────

export interface HybridMemoryFirestore {
  collection(path: string): {
    doc(id: string): {
      set(data: Record<string, unknown>): Promise<unknown>;
      get(): Promise<{ exists: boolean; data(): Record<string, unknown> | undefined }>;
    };
    orderBy(field: string, dir?: 'asc' | 'desc'): {
      limit(n: number): {
        get(): Promise<{ docs: Array<{ id: string; data(): Record<string, unknown> }> }>;
      };
    };
    add(data: Record<string, unknown>): Promise<{ id: string }>;
  };
}

export interface HybridMemoryOptions {
  /** Maximum number of memory vectors to keep in local DB (default: 10) */
  maxLocalItems?: number;
  /** Maximum items to fetch from Firestore on cold-start rehydration (default: 10) */
  rehydrationLimit?: number;
  /** Firestore collection path for this user's memories (default: users/{userId}/memory) */
  collectionPath?: string;
}

// ── Firestore Memory Document ─────────────────────────────────────────────────

interface FirestoreMemoryDoc {
  text: string;
  source?: string;
  createdAt: string;
  sessionId?: string;
}

// ── HybridMemoryAdapter ───────────────────────────────────────────────────────

/**
 * Server-side hybrid memory adapter.
 *
 * Wraps an existing MemorySearchManager (sqlite-vec) and adds:
 *   1. Firestore text sync on every insert
 *   2. Cold-start rehydration from Firestore
 *   3. 5-10 rule: cap local DB at maxLocalItems after each insert
 *
 * @param userId      - Firebase UID (the isolation key)
 * @param inner       - The underlying MemorySearchManager (sqlite-vec)
 * @param firestore   - Firestore client
 * @param embedText   - Function to embed text and insert into the local DB
 * @param opts        - Configuration options
 */
export class HybridMemoryAdapter implements MemorySearchManager {
  private readonly userId: string;
  private readonly inner: MemorySearchManager;
  private readonly firestore: HybridMemoryFirestore;
  private readonly embedAndInsert: (text: string, metadata?: Record<string, unknown>) => Promise<void>;
  private readonly pruneToLimit: (limit: number) => Promise<void>;
  private readonly maxLocalItems: number;
  private readonly rehydrationLimit: number;
  private readonly collectionPath: string;
  private rehydrated = false;

  constructor(
    userId: string,
    inner: MemorySearchManager,
    firestore: HybridMemoryFirestore,
    embedAndInsert: (text: string, metadata?: Record<string, unknown>) => Promise<void>,
    pruneToLimit: (limit: number) => Promise<void>,
    opts: HybridMemoryOptions = {},
  ) {
    this.userId = userId;
    this.inner = inner;
    this.firestore = firestore;
    this.embedAndInsert = embedAndInsert;
    this.pruneToLimit = pruneToLimit;
    this.maxLocalItems = opts.maxLocalItems ?? 10;
    this.rehydrationLimit = opts.rehydrationLimit ?? 10;
    this.collectionPath = opts.collectionPath ?? `users/${userId}/memory`;
  }

  // ── Rehydration ─────────────────────────────────────────────────────────────

  /**
   * On cold start (empty local DB), fetch the last N text snippets from
   * Firestore and re-embed them locally to populate the active memory window.
   *
   * Called lazily on the first search() call — transparent to callers.
   */
  private async ensureRehydrated(): Promise<void> {
    if (this.rehydrated) return;
    this.rehydrated = true; // Set eagerly to prevent concurrent rehydration

    try {
      const snapshot = await this.firestore
        .collection(this.collectionPath)
        .orderBy('createdAt', 'desc')
        .limit(this.rehydrationLimit)
        .get();

      if (snapshot.docs.length === 0) return; // New user — nothing to rehydrate

      logger.info(`[HybridMemory:${this.userId}] Rehydrating ${snapshot.docs.length} memories from Firestore`);

      // Re-embed in reverse order (oldest first) so the local DB is in chronological order
      const docs = [...snapshot.docs].reverse();
      for (const doc of docs) {
        const data = doc.data() as unknown as FirestoreMemoryDoc;
        if (data.text) {
          await this.embedAndInsert(data.text, { source: data.source, sessionId: data.sessionId }).catch((e) => {
            logger.warn(`[HybridMemory:${this.userId}] Rehydration embed failed for doc ${doc.id}:`, e);
          });
        }
      }

      logger.info(`[HybridMemory:${this.userId}] Rehydration complete`);
    } catch (err) {
      // Rehydration failure is non-fatal — memory starts empty, builds up fresh
      logger.warn(`[HybridMemory:${this.userId}] Rehydration failed (starting fresh):`, err);
    }
  }

  // ── Memory Insert ───────────────────────────────────────────────────────────

  /**
   * Adds a new memory item:
   *   1. Syncs text to Firestore (no vector — text only)
   *   2. Embeds locally and inserts into sqlite-vec
   *   3. Prunes local DB to maxLocalItems (5-10 rule)
   *
   * @param text      - The text to remember
   * @param metadata  - Optional metadata (source, sessionId, etc.)
   */
  async remember(text: string, metadata: Record<string, unknown> = {}): Promise<void> {
    const doc: FirestoreMemoryDoc = {
      text,
      source: metadata['source'] as string | undefined,
      sessionId: metadata['sessionId'] as string | undefined,
      createdAt: new Date().toISOString(),
    };

    // 1. Sync text to Firestore (async, non-blocking for caller)
    this.firestore
      .collection(this.collectionPath)
      .add({ ...doc, userId: this.userId })
      .catch((err) => {
        logger.warn(`[HybridMemory:${this.userId}] Firestore sync failed (local insert continues):`, err);
      });

    // 2. Embed and insert locally (this is the fast path — local sqlite-vec)
    await this.embedAndInsert(text, metadata);

    // 3. Apply 5-10 rule: keep only the most recent maxLocalItems vectors
    await this.pruneToLimit(this.maxLocalItems);
  }

  // ── MemorySearchManager Implementation ────────────────────────────────────

  async search(
    query: string,
    opts?: { maxResults?: number; minScore?: number; sessionKey?: string },
  ): Promise<MemorySearchResult[]> {
    // Lazily rehydrate on first search
    await this.ensureRehydrated();
    return this.inner.search(query, opts);
  }

  async readFile(params: {
    relPath: string;
    from?: number;
    lines?: number;
  }): Promise<{ text: string; path: string }> {
    return this.inner.readFile(params);
  }

  status(): MemoryProviderStatus {
    const inner = this.inner.status();
    return {
      ...inner,
      // Annotate with hybrid adapter info
      custom: {
        ...inner.custom,
        hybrid: {
          userId: this.userId,
          maxLocalItems: this.maxLocalItems,
          rehydrated: this.rehydrated,
          firestorePath: this.collectionPath,
        },
      },
    };
  }

  async probeEmbeddingAvailability(): Promise<MemoryEmbeddingProbeResult> {
    return this.inner.probeEmbeddingAvailability();
  }

  async probeVectorAvailability(): Promise<boolean> {
    return this.inner.probeVectorAvailability();
  }

  async close(): Promise<void> {
    return this.inner.close?.();
  }

  /** Sync delegate — triggers a full re-sync of the local index */
  async sync(params?: {
    reason?: string;
    force?: boolean;
    progress?: (update: { completed: number; total: number; label?: string }) => void;
  }): Promise<void> {
    return this.inner.sync?.(params);
  }
}
